import type { Meta, StoryObj } from '@storybook/vue3';
import VrxColorPalette from './VrxColorPalette.vue';
declare const meta: Meta<typeof VrxColorPalette>;
export default meta;
type ColorStory = StoryObj<typeof VrxColorPalette>;
export declare const Primary: ColorStory;
export declare const Secondary: ColorStory;
export declare const Neutral: ColorStory;
export declare const Error: ColorStory;
export declare const Root: ColorStory;
