import { Meta, StoryObj } from "@storybook/vue3";
import VrxGrid from '../../components/VrxGrid/VrxGrid.vue';
declare const meta: Meta<typeof VrxGrid>;
export default meta;
type GridStories = StoryObj<typeof VrxGrid>;
export declare const Primary: GridStories;
export declare const Filtrable: GridStories;
export declare const Selectable: GridStories;
export declare const Multiselectable: GridStories;
export declare const Editable: GridStories;
export declare const Static_Content: GridStories;
export declare const Colspan: GridStories;
