import type { Meta, StoryObj } from '@storybook/vue3';
import VrxSelect from './VrxSelect.vue';
declare const meta: Meta<typeof VrxSelect>;
export default meta;
type SelectStories = StoryObj<typeof VrxSelect>;
export declare const Primary: SelectStories;
export declare const Labeled: SelectStories;
export declare const Searchable: SelectStories;
export declare const Selected: SelectStories;
export declare const Multiselect: SelectStories;
export declare const Icon: SelectStories;
export declare const Disabled: SelectStories;
export declare const Invalid: SelectStories;
export declare const Variant: SelectStories;
